### ISSUE TITLE
Local - Liquid Exception: Failed to get header. in _posts/design/2014-09-15-gallery.md

### ISSUE THREAD

**Issue by felixinx** [Phlow/feeling-responsive#35]
Hi,

Here is my problem. When I run `jekyll serve` on my computer, I get an error;
`Liquid Exception: Failed to get header. in _posts/design/2014-09-15-gallery.md`.
This is weird, because there are no header on this post!

The file;
```markdown
---
layout: page
subheadline:  "Templates"
title:  "A Beautiful Gallery"
teaser: "Wanna create a responsive gallery to showcase your portfolio, recent photos or images? It's quite easy thanks to Foundation and <a href='http://foundation.zurb.com/docs/components/clearing.html'>Clearing Lightbox</a>."
categories:
    - design
tags:
    - post format
image:
   thumb: "unsplash_7_thumb.jpg"
---
You just need to choose a template like the [`page`][3]- or [`page-fullwidth`][4]-template and than use some foundation magic.

<ul class="clearing-thumbs small-block-grid-3" data-clearing>
  <li><a href="{{ site.url }}/images/unsplash_1.jpg"><img  data-caption="All images by Unsplash.com" class="th" src="{{ site.url }}/images/unsplash_1_thumb.jpg"></a></li>
  <li><a href="{{ site.url }}/images/unsplash_2.jpg"><img  data-caption="All images by Unsplash.com" class="th" src="{{ site.url }}/images/unsplash_2_thumb.jpg"></a></li>
  <li><a href="{{ site.url }}/images/unsplash_3.jpg"><img  data-caption="All images by Unsplash.com" class="th" src="{{ site.url }}/images/unsplash_3_thumb.jpg"></a></li>
  <li><a href="{{ site.url }}/images/unsplash_4.jpg"><img  data-caption="All images by Unsplash.com" class="th" src="{{ site.url }}/images/unsplash_4_thumb.jpg"></a></li>
  <li><a href="{{ site.url }}/images/unsplash_5.jpg"><img  data-caption="All images by Unsplash.com" class="th" src="{{ site.url }}/images/unsplash_5_thumb.jpg"></a></li>
  <li><a href="{{ site.url }}/images/unsplash_6.jpg"><img  data-caption="All images by Unsplash.com" class="th" src="{{ site.url }}/images/unsplash_6_bus_thumb.jpg"></a></li>
</ul>

## Clearing Lightbox Code

[Clearing Lightbox][1] is so flexible especially when using the [block grid][2]. For extensive documentation visit the [foundation docs][1].

{% highlight html %}
<ul class="clearing-thumbs small-block-grid-3" data-clearing>
  <li><a href="path/to/your/img"><img data-caption="caption 1" src="path/to/your/thumbnail"></a></li>
  <li><a href="path/to/your/img"><img data-caption="caption 2" src="path/to/your/thumbnail"></a></li>
  <li><a href="path/to/your/img"><img data-caption="caption 3" src="path/to/your/thumbnail"></a></li>
</ul>
{% endhighlight %}



## Other Post Formats
{: .t60 }
{% include list-posts.html tag='post format' %}



 [1]: http://foundation.zurb.com/docs/components/clearing.html
 [2]: http://foundation.zurb.com/docs/components/block_grid.html
 [3]: {{ site.url }}/design/page/
 [4]: {{ site.url }}/design/page-fullwidth/
```

The repo of my file : https://github.com/felixinx/felixinx.github.io
Jekyll version 2.5.3.

Thanks :+1:

**Comment by Phlow** [comment]
Hey @felixinx, I downloaded you repository, ran Jekyll 2.5.3 and got no errors... working fine over here. I have no idea, what's wrong.

**Comment by felixinx** [comment]
Are you on Windows? It could be a Windows error specific.

**Comment by TWiStErRob** [comment]
I'm on Windows 7 and don't remember this error, I copy-pasted the above code to my current Jekyll site based on Feeling Responsive and it had no problems. I suggest a `jekyll serve --trace`, maybe it reveals more.

**Comment by felixinx** [comment]
All the result;
```ruby
jekyll serve --trace
Configuration file: H:/www/GitHub/felixinx.github.io/_config.yml
            Source: H:/www/GitHub/felixinx.github.io
       Destination: H:/www/GitHub/felixinx.github.io/_site
      Generating...
  Liquid Exception: Failed to get header. in _posts/design/2014-09-15-gallery.md
C:/Ruby21/lib/ruby/gems/2.1.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:381:in `rescue in get_header': Failed to get header. (MentosError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:362:in `get_header'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:259:in `block in mentos'
        from C:/Ruby21/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
        from C:/Ruby21/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
        from C:/Ruby21/lib/ruby/2.1.0/timeout.rb:35:in `catch'
        from C:/Ruby21/lib/ruby/2.1.0/timeout.rb:35:in `catch'
        from C:/Ruby21/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:233:in `mentos'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:215:in `highlight'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/tags/highlight.rb:82:in `render_pygments'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/tags/highlight.rb:52:in `render'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:233:in `do_layout'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/post.rb:261:in `render'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from C:/Ruby21/bin/jekyll:23:in `load'
        from C:/Ruby21/bin/jekyll:23:in `<main>'
```

**Comment by TWiStErRob** [comment]
Just realized that Google is full of solutions: https://www.google.com/search?q=failed+to+get+header
Based on those results it's your Python version, most likely yours is 3.x, here are my versions:
 * `ruby --version`: ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
 * `python --version`: Python 2.7.10
 * `bundle exec jekyll --version`: jekyll 2.4.0
 * `bundle update | find "pygments"`: Using pygments.rb 0.6.3

**Comment by felixinx** [comment]
Yes, I am in `3.4.2`. I will install the 2 version soon.
